### ISSUE TITLE
Support python 3.6

### ISSUE THREAD

**Issue by hotohoto** [automl/HpBandSter#106]
I got this traceback and I cannot upgrade scipy to 1.6.2 for `factorial`.

```
Traceback (most recent call last):
  File "/home/hotohoto/dev/mlcore/run_rnn_autotune_benchmark.py", line 268, in <module>
    main()
  File "/home/hotohoto/dev/mlcore/run_rnn_autotune_benchmark.py", line 252, in main
    train_model_response = train_controller.execute(train_model_request)
  File "/home/hotohoto/dev/mlcore/mlcore/timeseries/usecases/utils.py", line 144, in f
    return method(*args, **kwargs, temp_context=temp_context)
  File "/home/hotohoto/dev/mlcore/mlcore/timeseries/api/train_model.py", line 563, in execute
    results.append(uc.execute(*args, **kwargs))
  File "/home/hotohoto/dev/mlcore/mlcore/timeseries/usecases/utils.py", line 144, in f
    return method(*args, **kwargs, temp_context=temp_context)
  File "/home/hotohoto/dev/mlcore/mlcore/timeseries/usecases/run_data_train_inference.py", line 135, in execute
    afe_options=afe_options,
  File "/home/hotohoto/dev/mlcore/mlcore/timeseries/usecases/fit_pipeline.py", line 90, in execute
    prediction_options,
  File "/home/hotohoto/dev/mlcore/mlcore/timeseries/usecases/fit_single_model.py", line 67, in execute
    step=self.step,
  File "/home/hotohoto/dev/mlcore/mlcore/timeseries/usecases/fit_single_model.py", line 200, in _compute_fit
    **model_options.autotune_options.to_fit_autotune_args(),
  File "/home/hotohoto/dev/mlcore/mlcore/models/recurrent_neural_net.py", line 837, in fit_autotune
    ray_search_algorithm=TuneBOHB(metric="loss", mode="min", seed=self.seed),
  File "/home/hotohoto/.pyenv/versions/3.6.10/envs/mlcore/lib/python3.6/site-packages/ray/tune/suggest/bohb.py", line 116, in __init__
    from hpbandster.optimizers.config_generators.bohb import BOHB
  File "/home/hotohoto/.pyenv/versions/3.6.10/envs/mlcore/lib/python3.6/site-packages/hpbandster/optimizers/__init__.py", line 3, in <module>
    from hpbandster.optimizers.bohb import BOHB
  File "/home/hotohoto/.pyenv/versions/3.6.10/envs/mlcore/lib/python3.6/site-packages/hpbandster/optimizers/bohb.py", line 14, in <module>
    from hpbandster.optimizers.config_generators.bohb import BOHB as CG_BOHB
  File "/home/hotohoto/.pyenv/versions/3.6.10/envs/mlcore/lib/python3.6/site-packages/hpbandster/optimizers/config_generators/bohb.py", line 12, in <module>
    import statsmodels.api as sm
  File "/home/hotohoto/.pyenv/versions/3.6.10/envs/mlcore/lib/python3.6/site-packages/statsmodels/api.py", line 16, in <module>
    from .discrete.discrete_model import (Poisson, Logit, Probit,
  File "/home/hotohoto/.pyenv/versions/3.6.10/envs/mlcore/lib/python3.6/site-packages/statsmodels/discrete/discrete_model.py", line 45, in <module>
    from statsmodels.distributions import genpoisson_p
  File "/home/hotohoto/.pyenv/versions/3.6.10/envs/mlcore/lib/python3.6/site-packages/statsmodels/distributions/__init__.py", line 2, in <module>
    from .edgeworth import ExpandedNormal
  File "/home/hotohoto/.pyenv/versions/3.6.10/envs/mlcore/lib/python3.6/site-packages/statsmodels/distributions/edgeworth.py", line 7, in <module>
    from scipy.misc import factorial
ImportError: cannot import name 'factorial'
```

**Comment by mostafa-mahmoud** [comment]
@hotohoto Try updating `statsmodels` package.
